version: '3'

services:
  # mysql
  primal-honey-db:
    image: mysql:8.0
    container_name: echo-demo-mysql8
    environment:
      MYSQL_DATABASE: echo-demo
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "13326:3306"
    volumes:
      - ./logs:/var/log/mysql
      - ./docker/mysql:/etc/mysql/conf.d
      - mysql-volume:/var/lib/mysql  # `docker volume create echo-demo-mysql8_volume`を予め実行しておく
      
volumes:
  mysql-volume:
    external:
      name: primal-honey-mysql8_volume
